# 1 Data Types


In [8]:
x = np.float32(1.0)

In [9]:
x

1.0

In [10]:
y = np.int_([1,2,4])

y

array([1, 2, 4])

In [11]:
z = np.arange(-3,3,dtype=np.uint8)

In [12]:
z

array([253, 254, 255,   0,   1,   2], dtype=uint8)

阵列类型也可以用字符代码来表示，主要是为了保持与旧的包（如Numeric）的向后兼容性。一些文档可能仍然会提及这些类型，例如：

In [14]:
a = np.array([1,2,3],dtype='f')

b = np.array([-5,-1,4,5],dtype=np.uint8)

In [15]:
a

array([1., 2., 3.], dtype=float32)

In [16]:
b

array([251, 255,   4,   5], dtype=uint8)

In [17]:
z.astype(float)

array([253., 254., 255.,   0.,   1.,   2.])

In [19]:
np.int8(z)

array([-3, -2, -1,  0,  1,  2], dtype=int8)

In [20]:
z.dtype

dtype('uint8')

dtype对象还包含有关类型的信息，如它的位宽和字节顺序。数据类型也可以间接用于查询该类型的属性，例如它是否是一个整数。

In [21]:
d = np.dtype(int)

In [22]:
d

dtype('int32')

In [23]:
np.issubdtype(d,np.integer)

True

In [25]:
np.issubdtype(d,np.floating)

False

NumPy 通常以数组标量 (一个带有关联 dtype 的标量) 的形式返回数组元素。数组标量不同于Python标量，但大多数情况下它们可以互换使用 (主要的例外是Python的v2.x以上的版本，在这些版本中，整数组标量不能作为列表和元组的索引)。也有一些例外，比如当代码需要一个标量的非常特定的属性，或者当它特别检查一个值是否是 Python 标量时。一般来说，通过使用相应的Python类型函数(例如int、float、complex、str、unicode)显式地将数组标量转换为Python标量，问题就很容易解决。

使用数组标量的主要优点是它们保留了数组类型(Python可能没有匹配的标量类型可用，例如int16)。因此，使用数组标量可以确保数组和标量之间的行为是相同的，不管值是否在数组中。NumPy标量也有许多与数组相同的方法。

NumPy数值类型的固定大小，当一个值需要的内存大于数据类型的可用内存时，可能会导致溢出错误。例如，numpy.power对于64位整数正确地评估100 * 10 ** 8，但对于32位整数却给出1874919424（不正确）。

In [26]:
np.power(100,8,dtype=np.int64)

10000000000000000

In [27]:
np.power(100,8,dtype=np.int32)

1874919424

# 2 Structured arrays(结构矩阵）

In [2]:
import numpy as np

x = np.array([('Rex',9,81.0),('Fido',3,27.0)],dtype=[('name','U10'),('age','i4'),('weight','f4')])

In [3]:
x

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [4]:
x[1]

('Fido', 3, 27.)

In [5]:
x['age']

array([9, 3])

In [6]:
x['age']=5

In [7]:
x

array([('Rex', 5, 81.), ('Fido', 5, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])