# Pytorch教程


## 1 Getting Started

In [1]:
from __future__ import print_function
import torch
x = torch.rand(5,3)
print(x)

tensor([[0.6406, 0.0381, 0.1101],
        [0.4794, 0.0882, 0.3598],
        [0.3074, 0.6615, 0.6951],
        [0.8943, 0.1857, 0.8353],
        [0.5862, 0.0350, 0.1165]])


In [2]:
import torch
torch.cuda.is_available()

True

## 2 Deep Learning with PyTorch:60 minnute blitz

**Tensors**

In [3]:
from __future__ import print_function
import torch

In [4]:
x = torch.empty(5,3)

print(x)

tensor([[4.2246e-39, 1.0286e-38, 1.0653e-38],
        [1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38]])


In [5]:
y = torch.rand(5,3)

print(y)

tensor([[0.1145, 0.9702, 0.7530],
        [0.7579, 0.9220, 0.0424],
        [0.8180, 0.7831, 0.9887],
        [0.3857, 0.7545, 0.5047],
        [0.7996, 0.0504, 0.5500]])


In [6]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.tensor([[5.5,3],[7,8.9]])

In [9]:
x

tensor([[5.5000, 3.0000],
        [7.0000, 8.9000]])

或基于现有张量创建一个张量。这些方法将重用输入张量的属性，例如dtype，除非用户提供新的值。

In [10]:
x = x.new_ones(5,3,dtype=torch.double)

In [11]:
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [12]:
x = torch.randn_like(x,dtype=torch.float)

In [13]:
print(x)

tensor([[-0.5572,  0.0364, -0.5343],
        [ 1.2312,  1.3603,  0.7347],
        [-1.5149, -0.5823,  1.4924],
        [ 1.6598,  0.3817, -2.3977],
        [ 0.1060, -0.7908,  1.4388]])
